### ISSUE TITLE
[docs] Need documentation for Go SDK

### ISSUE THREAD

**Issue by hhunter-ms** [dapr-sandbox/components-go-sdk#20]
Go SDK is available to use, but there is no documentation for it.
Use documentation in [dapr-sandbox/components-dotnet-sdk](https://github.com/dapr-sandbox/components-dotnet-sdk/tree/main/daprdocs/content/en/dotnet-sdk-docs) as model.
I can support.

Related docs issue: dapr/docs#3189

**Comment by hhunter-ms** [comment]
@philliphoff

**Comment by philliphoff** [comment]
@hhunter-ms I have a draft PR (#21) for this initial documentation. Feel free to review and add feedback.
